name: "Build Docker Image Frontend"
description: |
  "Faz o build das imagens do Backend e Frontend"

inputs:
  registry_name:
    description: "Docker Registry"
    required: true
  project_name:
    description: "Project Name"
    required: true
  docker_login:
    description: "Docker username"
    required: true
  docker_password:
    description: "Docker password"
    required: true
  docker_back_front: 
    description: "Backend or Frontend"
    required: true
  git_branch:
    description: "Branch"
    required: true
  dockerfile_name:
    description: "Dockerfile Name"
    default: "DockerFile"
  tag:
    description: "Tag da imagem. Default: latest"

runs:
  using: "composite"
  steps:
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v2.6.0

    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: ${{inputs.docker_login}}
        password: ${{inputs.docker_password}}
        logout: true

    - name: Set the tag
      shell: bash
      run: |
        if [[ "${{inputs.git_branch}}" =~ production-v.* ]]; then
          echo "final_tag=-latest" >> $GITHUB_ENV
        elif [[ "${{inputs.git_branch}}" =~ "staging" ]]
        then
          echo "final_tag=-staging" >> $GITHUB_ENV
        else
          echo "final_tag=-${{inputs.tags}}" >> $GITHUB_ENV
        fi
        
    - name: Print final_tag
      shell: bash
      run: |
        echo "---------------------------------------------------------------------------------------"
        echo $final_tag
        echo "---------------------------------------------------------------------------------------"

    - name: Tree
      shell: bash
      run: ls -la

    - name: Extract production-v
      shell: bash
      run: |
        echo "${{inputs.git_branch}}"
        EXTRACT_PRODUCTION_STRING=$(echo "${{inputs.git_branch}}" | sed 's/.*production-//')
        echo "EXTRACT_PRODUCTION_STRING=$EXTRACT_PRODUCTION_STRING" >> $GITHUB_ENV
        echo "Extract: $EXTRACT_PRODUCTION_STRING"

    - name: Build and push Docker Backend
      uses: docker/build-push-action@v4.0.0
      with:
        context: .
        file: ${{ inputs.dockerfile_name }}
        labels: |
          --label source-branch=$GITHUB_REF_NAME
          --label build-commit=$GITHUB_SHA
          --label repository=$GITHUB_REPOSITORY
          --label source-build=github
        tags: |
          ${{inputs.registry_name}}/${{inputs.project_name}}:${{inputs.docker_back_front}}${{env.final_tag}},
          ${{inputs.registry_name}}/${{inputs.project_name}}:${{inputs.docker_back_front}}-${{ env.EXTRACT_PRODUCTION_STRING }}
        push: true
