name: "Build Docker Image"
description: "Faz o build das imagens tanto do backend quanto do frontend e faz o push para o registry"

inputs:
  registry_name:
    description: "Docker Registry"
    required: true
  project_name:
    description: "Project Name"
    required: true
  docker_login:
    description: "Docker username"
    required: true
  docker_password:
    description: "Docker password"
    required: true
  tag:
    description: "Tag da imagem. Default: latest"

runs:
  using: "composite"
  steps:
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v2.6.0

    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: ${{inputs.docker_login}}
        password: ${{inputs.docker_password}}
        logout: true

    - name: Set the tag
      shell: bash
      run: |
        if [ -z "${{inputs.tags}}" ]
        then
          echo "final_tag=-latest" >> $GITHUB_ENV
        elif [[ "${{ github.ref_name }}" == "staging" ]]
        then
          echo "final_tag=-staging" >> $GITHUB_ENV
        else
          echo "final_tag=-${{inputs.tags}}" >> $GITHUB_ENV
        fi

    - name: Build and push Docker Backend
      uses: docker/build-push-action@v4.0.0
      with:
        context: .
        file: Dockerfile.backend
        labels: |
          --label source-branch=$GITHUB_REF_NAME
          --label build-commit=$GITHUB_SHA
          --label repository=$GITHUB_REPOSITORY
          --label source-build=github
        tags: ${{inputs.registry_name}}/${{inputs.project_name}}:backend${{env.final_tag}}
        push: true

    - name: Build and push Docker Frontend
      uses: docker/build-push-action@v4.0.0
      with:
        context: .
        file: Dockerfile.frontend
        labels: |
          --label source-branch=$GITHUB_REF_NAME
          --label build-commit=$GITHUB_SHA
          --label repository=$GITHUB_REPOSITORY
          --label source-build=github
        tags: ${{inputs.registry_name}}/${{inputs.project_name}}:frontend${{env.final_tag}}
        push: true
